"""悬壶 Harness 与 LangGraph Agent Runtime 公共契约。

本包是 LangGraph v2 执行体系的最小运行底座，不包含临床逻辑。

L1-2 范围：
- ``XuanhuGraphState``：对齐实施计划 §6.2 的最小可序列化执行游标状态。
- ``MainGraph``：START -> command router -> 占位节点 -> END/blocked/manual terminal。
- 命令路由：message/advance/review/recover/unknown。

禁止事项（L1-2 边界）：
- 不接入业务 Agent。
- 不接入真实模型、Redis、RAG 或患者数据。
- 不接入 FastAPI 生产路由。
- 不接入 AsyncPostgresSaver 生产 checkpointer（留给 L1-3）。
- 不实现 GraphRunner/stream（留给 L1-4）。
"""

from __future__ import annotations

from app.agent_runtime.completeness_policy import (
    COMPLETENESS_COMPLAINT_TEN_QUESTION_RULES,
    COMPLETENESS_DIMENSION_RULES,
    COMPLETENESS_POLICY_CONFIG,
    CompletenessPolicyFailureCode,
    CompletenessPolicyInputError,
    FrozenCompletenessRuleRegistry,
    canonicalize_completeness_input,
    completeness_gate_result,
    completeness_to_gate_result_schema,
    evaluate_completeness_policy,
)
from app.agent_runtime.context import (
    ContextBuilder,
    ContextBuilderError,
    ContextPacket,
    PromptLayer,
    PromptMessage,
    PseudonymKeyProvider,
    PseudonymKeyUnavailable,
    TemplateValidationError,
    TokenBudget,
    TokenBudgetExceeded,
    pseudonym,
    render_template,
)
from app.agent_runtime.intake_verifier import (
    INTAKE_AGENT_NAME,
    INTAKE_AGENT_VERSION,
    INTAKE_ALLOWED_STAGES,
    INTAKE_PROMPT_VERSION,
    INTAKE_VERIFIER_CHAIN,
    IntakeCheckResult,
    IntakeCheckStatus,
    IntakeOutputBoundaryError,
    IntakeVerificationFailureCode,
    IntakeVerificationReport,
    IntakeVerifierName,
    canonicalize_intake_output,
    validate_intake_preflight,
    verify_intake_artifact,
)
from app.agent_runtime.reducer import (
    DomainDelta,
    DomainReducerError,
    DomainState,
    ReducerErrorCode,
    domain_delta_digest,
    reduce_domain_state,
    validate_domain_delta,
)
from app.agent_runtime.repository import (
    DOMAIN_STATE_COMMITTED,
    CommitResult,
    DomainRepository,
    OutboxErrorCode,
    OutboxMessage,
    OutboxRepository,
    PostgresDomainRepository,
    RepositoryError,
    RepositoryErrorCode,
)
from app.agent_runtime.runtime import AgentRuntime, RuntimeErrorBase, RuntimeRunRecorder
from app.agent_runtime.specs import (
    AgentSpec,
    Capability,
    FailurePolicy,
    ModelPolicy,
    RunArtifact,
    RunSpec,
    RuntimeErrorCode,
    TokenUsage,
)
from app.agent_runtime.triage_policy import (
    TRIAGE_RED_FLAG_RULES,
    TriagePolicyFailureCode,
    TriagePolicyInputError,
    TriageRule,
    canonicalize_triage_input,
    evaluate_triage_policy,
    to_gate_result_schema,
    triage_gate_result,
)
from app.agent_runtime.verifiers import (
    DEFAULT_VERIFIER_CHAIN,
    CheckResult,
    CheckStatus,
    DeltaLegalityVerifier,
    OutputTypeVerifier,
    PrerequisiteVerifier,
    ProvenanceVersionVerifier,
    SchemaVerifier,
    VerificationContext,
    VerificationFailureClass,
    VerificationFailureCode,
    VerificationReport,
    Verifier,
    VerifierChain,
    VerifierName,
)

__all__ = [
    "AgentRuntime",
    "RuntimeErrorBase",
    "RuntimeRunRecorder",
    "AgentSpec",
    "Capability",
    "FailurePolicy",
    "ModelPolicy",
    "RunArtifact",
    "RunSpec",
    "RuntimeErrorCode",
    "TokenUsage",
    "COMPLETENESS_COMPLAINT_TEN_QUESTION_RULES",
    "COMPLETENESS_DIMENSION_RULES",
    "COMPLETENESS_POLICY_CONFIG",
    "CompletenessPolicyFailureCode",
    "CompletenessPolicyInputError",
    "FrozenCompletenessRuleRegistry",
    "canonicalize_completeness_input",
    "completeness_gate_result",
    "completeness_to_gate_result_schema",
    "evaluate_completeness_policy",
    "TRIAGE_RED_FLAG_RULES",
    "TriagePolicyFailureCode",
    "TriagePolicyInputError",
    "TriageRule",
    "canonicalize_triage_input",
    "evaluate_triage_policy",
    "to_gate_result_schema",
    "triage_gate_result",
    "ContextBuilder",
    "ContextBuilderError",
    "ContextPacket",
    "PromptLayer",
    "PromptMessage",
    "PseudonymKeyProvider",
    "PseudonymKeyUnavailable",
    "TemplateValidationError",
    "TokenBudget",
    "TokenBudgetExceeded",
    "pseudonym",
    "render_template",
    "INTAKE_AGENT_NAME",
    "INTAKE_AGENT_VERSION",
    "INTAKE_ALLOWED_STAGES",
    "INTAKE_PROMPT_VERSION",
    "INTAKE_VERIFIER_CHAIN",
    "IntakeCheckResult",
    "IntakeCheckStatus",
    "IntakeOutputBoundaryError",
    "IntakeVerificationFailureCode",
    "IntakeVerificationReport",
    "IntakeVerifierName",
    "canonicalize_intake_output",
    "validate_intake_preflight",
    "verify_intake_artifact",
    "DomainDelta",
    "DomainReducerError",
    "DomainState",
    "ReducerErrorCode",
    "domain_delta_digest",
    "reduce_domain_state",
    "validate_domain_delta",
    "DOMAIN_STATE_COMMITTED",
    "CommitResult",
    "DomainRepository",
    "OutboxErrorCode",
    "OutboxMessage",
    "OutboxRepository",
    "PostgresDomainRepository",
    "RepositoryError",
    "RepositoryErrorCode",
    "DEFAULT_VERIFIER_CHAIN",
    "CheckResult",
    "CheckStatus",
    "DeltaLegalityVerifier",
    "OutputTypeVerifier",
    "PrerequisiteVerifier",
    "ProvenanceVersionVerifier",
    "SchemaVerifier",
    "VerificationContext",
    "VerificationFailureClass",
    "VerificationFailureCode",
    "VerificationReport",
    "Verifier",
    "VerifierChain",
    "VerifierName",
]
